#pragma once

#include <algorithm>
#include <cassert>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <queue>
#include <stdexcept>
#include <sstream>
#include <string>
#include <sstream>
#include <unordered_map>
#include <vector>

#include "gason.h"
#include "glm/glm.hpp"
#include "stb_image.h"

#include "Asset/Asset.h"
#include "Asset/AssetManager.h"
#include "Asset/DataAsset.h"
#include "Asset/MaterialAsset.h"
#include "Asset/MeshAsset.h"
#include "Asset/ModelAsset.h"
#include "Asset/NonPbrMaterialAsset.h"
#include "Asset/PbrMaterialAsset.h"
#include "Asset/SceneAsset.h"
#include "Asset/TextureAsset.h"
#include "Audio/AudioManager.h"
#include "Containers/DataArray.h"
#include "Containers/Queue.h"
#include "Core/Checksum.h"
#include "Core/Core.h"
#include "Core/DynamicLibrary.h"
#include "Core/GameClock.h"
#include "Core/GameException.h"
#include "Core/GameTime.h"
#include "Core/MatrixHelper.h"
#include "Core/Platform.h"
#include "Core/RTTI.h"
#include "Core/ServiceLocator.h"
#include "Core/Singleton.h"
#include "Core/StreamHelper.h"
#include "Core/StringID.h"
#include "Core/Types.h"
#include "Core/VectorHelper.h"
#include "Gameplay/Actor.h"
#include "Graphics/Blackboard.h"
#include "Graphics/FrameGraph.h"
#include "Graphics/Mesh.h"
#include "Graphics/Renderer.h"
#include "Graphics/RendererTypes.h"
#include "Graphics/RenderPass.h"
#include "Graphics/RenderPassBuilder.h"
#include "Graphics/RenderPrimitive.h"
#include "Graphics/Shader.h"
#include "Graphics/Texture.h"
#include "Graphics/TextureLoader.h"
#include "Input/InputEnums.h"
#include "Input/InputManager.h"
#include "Logging/Logger.h"
#include "Memory/MemoryAllocator.h"
#include "Memory/MemoryManager.h"
#include "Memory/StackAllocator.h"
#include "Window/WindowContext.h"
#include "Window/WindowManager.h"
